name: Check Code

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer, prestissimo
        coverage: none
        
      
    - name: Install Shopware
      run: composer install

    - name: Check code
      run: vendor/bin/php-cs-fixer  fix --dry-run -v --allow-risky=yes --format=junit | tee php-cs-fixer.xml
    
    - name: Junit FIle
      run: cat php-cs-fixer.xml
    
    - uses: shyim/junit-report-annotations-action@0.1.4
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        stripFromPath: 'sw5/'
        path: php-cs-fixer.xml
