name: Check Code

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check code
      run: ./psh.phar check-code
    
    - name: Junit FIle
      run: cat php-cs-fixer.xml
    
    - uses: shyim/junit-report-annotations-action@master
      with:
        path: php-cs-fixer.xml
