name: PHPUnit (PHP)

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        mysql: ['mysql:8.0.19', 'mariadb:10.1', 'mariadb:10.4']
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer, prestissimo
        
    - name: Start MySQL
      run: ./.github/setup-db.sh ${{ matrix.mysql }}
      
    - name: Install Shopware
      run: ./psh.phar init --DB_HOST=127.0.0.1 --DB_USER=shopware --DB_PASSWORD=shopware --SW_HOST=localhost

    - name: PHPUnit
      run: ./psh.phar unit-fast --DB_HOST=127.0.0.1 --DB_USER=shopware --DB_PASSWORD=shopware --SW_HOST=localhost
