name: PHPUnit (PHP)

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4']
    runs-on: ubuntu-latest
    env:
      DB: mysql:5.7

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer, prestissimo
        
    - name: Start MySQL
      run: ./.travis/setup-db.sh
      
    - name: Install Shopware
      run: ./psh.phar init --DB_HOST=127.0.0.1 --DB_USER=travis --DB_PASSWORD=travis --SW_HOST=localhost

    - name: Check code
      run: ./psh.phar unit-fast --DB_HOST=127.0.0.1 --DB_USER=travis --DB_PASSWORD=travis --SW_HOST=localhost
